[phases.install]
cmds = ["npm install --prefix server && npm install --prefix client"]

[phases.build]
cmds = ["npm run build --prefix client && npm run build --prefix server"]

[start]
cmd = "npm run start --prefix server"
